# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

favorite:
  drink: coffee
  food: pizza
pizzaToppings:
  - mushrooms
  - cheese
  - peppers
  - onions
