{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    name: node-example
    namespace: default
spec:
  maxReplicas: {{ .Values.hpa.max }}
  minReplicas: {{ .Values.hpa.min }}
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: node-example
  targetCPUUtilizationPercentage: {{ .Values.hpa.utilization }}
{{- end -}}